### ISSUE TITLE
icons got all black

### ISSUE THREAD

**Issue by zx1986** [kudakurage/LigatureSymbols#7]
Sorry, here is my first touch with LigatureSymbols:
http://i.imgur.com/JjCHI

here is my css:

``` css
/* http://kudakurage.com/ligature_symbols */

@font-face {
    font-family: 'LigatureSymbols';
    src: url('../font/LigatureSymbols.eot');
    src: url('../font/LigatureSymbols.eot?#iefix') format('embedded-opentype'),
         url('../font/LigatureSymbols.woff') format('woff'),
         url('../font/LigatureSymbols.ttf') format('truetype'),
         url('../font/LigatureSymbols.svg#LigatureSymbols') format('svg');
    src: url('../font/LigatureSymbols.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}

.lsf, .lsf-icon:before {
    font-family: 'LigatureSymbols';
    text-rendering: optimizeLegibility;
    -webkit-font-smoothing: antialiased;
       -moz-font-smoothing: antialiased;
        -ms-font-smoothing: antialiased;
         -o-font-smoothing: antialiased;
            font-smoothing: antialiased;
}

.lsf-icon:before {
    content: attr(title);
    margin-right: .3em;
    font-size: 130%;
}
```

here is my html:

``` html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    <title></title>

    <link rel="stylesheet" type="test/css" href="assets/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="assets/css/font-awesome.css">
    <link rel="stylesheet" type="text/css" href="assets/css/lsf.css">

    <script type="text/javascript" charset="utf-8" src="assets/js/modernizr.js"></script>
</head>
<body>
    <!--[if lt IE 7]>
        <p class="chromeframe"><a href="http://browsehappy.com/">You will live much happier without IE.</a></p>
    <![endif]-->

    <h1 class="lsf">love</h1>
    <h1 class="lsf-icon" title="chrome"></h1>

    <script type="text/javascript" charset="utf-8" src="assets/js/jquery.js"></script>
</body>
</html>
```
